### PR TITLE
Switch to ember browserify

### LINKED ISSUE #17: Overriding `require` causes ember loader to throw warnings
Example:

```cli
ember test
version: 2.3.0-beta.2
Built project successfully. Stored in "/Users/runspired/GitHub/flexi/tmp/class-tests_dist-TdmA0Cyi.tmp".
ok 1 PhantomJS 2.0 - JSCS - modules/flexi/components: modules/flexi/components/flexi-centered.js should pass jscs
    ---
        Log: |
            { type: 'warn',
              text: '\'unable to require.unsee, please upgrade loader.js to >= v3.3.0\'\n' }
    ...
```

I traced this down, and it appears a require override is inserted along with `highlight.js`, but examining the source shows it does not originate from `highlight.js` itself.  This addon passes highlight through `browserify`, I'm guessing browserify inserts the require.

### PR DESCRIPTION
**Pull request by AO16**
- Move from `broccoli-browserify` to `ember-browserify`
- Add in a blueprint that adds `ember-browserify` to project
- Fixes #17

### CODE REVIEW

**Comment by ef4** [comment]
Moving to ember-browserify is good. 

Is there a reason we can't just make is a `dependency` instead of using a blueprint?  Alternatively, if it really needs to be added to the containing application instead of nested, it should probably be listed as a `peerDependency`.

**Comment by AO16** [comment]
@ef4 I went ahead and moved that stuff out of the blueprint and just added as dependency.

**Comment by tim-evans** [comment]
This would be awesome! I'd love to use ember-code-snippet for our docs :)

**Comment by AO16** [comment]
👍

**Comment by AO16** [comment]
@ef4 would you be able to publish a new release with this in it?

**Comment by ef4** [comment]
I published 1.7.0 with this, and then realized it breaks apps that don't already have browserify as a top-level dependency. Reverted and published 1.8.0 to go back until this can be fixed.

**Comment by AO16** [comment]
@ef4 I was running through ember-browserify docs a bit. It seems like this is a known issue. 

Should I go ahead and move the addition of the addon back into the blueprint? I'm not sure how we would be able to guarantee that they run the blueprint gen again though. 

Open to recommendations.

**Comment by AO16** [comment]
What about an update to the readme? Requiring browersify installa and a major version bump?

**Comment by ef4** [comment]
Yes, that sounds about right.

 - major version bump
 - list ember-browserify in `peerDependencies` in package.json
 - if ember-browserify is not correctly installed, fail with a friendly message and instructions how to fix

**Pull request merged**
