### PR TITLE
Add ember-browserify

### PR DESCRIPTION
**Pull request by AO16**

### CODE REVIEW

**Comment by AO16** [comment]
Fixes issues left from #23

**Comment by akashdsouza** [comment]
Hi. Any updates on this?

**Comment by ef4** [comment]
Closing in favor of #39. Please try 2.0.0-alpha.1. If it's working out well for people it will become 2.0.0.

The breaking change is that we no longer include syntax highlighting for all 176 languages by default. More details in #39.

**Comment by akashdsouza** [comment]
Thanks for the update. I can confirm that 2.0.0-alpha.1 is working without any issues for me.

**Pull request closed without merging**
